### PR TITLE
feat: dashboard setup

### PR DESCRIPTION
**Pull request by fracergu**
- Added initial approach for Dashboard according to requisites
  - Implemented unit tests for Dashboard components
  - Added and configured routing
  - Added some dummy pages to check routing and Dashboard outlet
  - Added prettier to the project for code format consistency
  - Installed styled components

### CODE REVIEW

**Review by devvspaces — CHANGES_REQUESTED** [review]
This is nice, great initiative. Send screenshots of the pages you added

**Comment by devvspaces** [comment]
Did you add tailwind? @fracergu

**Comment by fracergu** [comment]
Hi @devvspaces 

Not yet, because I saw it subsequently to opening the PR and I didn't know if I was going to go ahead with it. Give me a moment and I'll replace styled-components with it.

I also have other suggestions for the frontend project, which would be a good time to implement since it still has very little content and would not be expensive:

- Replace `create-react-app` with `vite`. Vite is a packer that I see more appropriate and efficient for this application since it will not require excessive configuration and it will not have a large size, we could take advantage of its greater speed: [more information here](https://semaphoreci.com/blog/vite)

- Use typescript. Typescript has static typing that helps the compiler make sure that the code is correct. On the other hand, in JavaScript, no errors are detected by the compiler because it's dynamically typed.

These changes will make it more attractive to potential contributors and the frontend will be equipped with more cutting-edge technology, which will make its use and development much more efficient.

I could implement them after this PR without complications, if they are suitable, you can open an issue for it.

**Comment by devvspaces** [comment]
Yo, no need

**Comment by devvspaces** [comment]
I think styled-components is ok

**Comment by devvspaces** [comment]
Typescript and vite use it @fracergu

**Comment by fracergu** [comment]
As you prefer!

I already have the tailwind implementation ready as well. We can go ahead with whatever you prefer. I'm used to work with both and tailwind might be a bit more attractive for contributors, if you want we'll leave it with tailwind. 😉

**Comment by fracergu** [comment]
@devvspaces 

Here is the current status of the application with Tailwind and routing.

I haven't bothered much with the aesthetics because I think that should be addressed later in another issue. As you will see, the dashboard works correctly with its internal routing outlet.

[Grabación de pantalla desde 2023-10-22 10-50-23.webm](https://github.com/devvspaces/studypal/assets/17405480/34e61949-3de1-45eb-8e72-5c9025a91711)

**Review by devvspaces — APPROVED** [review]

**Comment by devvspaces** [comment]
@fracergu have you done the Vite migration or do i need to create an issue

**Comment by fracergu** [comment]
@devvspaces, no I didn't, please open an issue and assign it to me.

**Comment by devvspaces** [comment]
@fracergu comment here #27

**Pull request merged**
