### PR TITLE
feat: added basic backend setup with django and swagger

### PR DESCRIPTION
**Pull request by fracergu**

### CODE REVIEW

**Review by devvspaces — CHANGES_REQUESTED** [review]
Ensure you add a gitignore file to ignore all .pyc files

Use this gitignore

```
# Byte-compiled / optimized / DLL files
__pycache__/
*.py[cod]
*$py.class

# C extensions
*.so

# Distribution / packaging
.Python
build/
develop-eggs/
dist/
downloads/
eggs/
.eggs/
lib/
lib64/
parts/
sdist/
var/
wheels/
pip-wheel-metadata/
share/python-wheels/
*.egg-info/
.installed.cfg
*.egg
MANIFEST

# PyInstaller
#  Usually these files are written by a python script from a template
#  before PyInstaller builds the exe, so as to inject date/other infos into it.
*.manifest
*.spec

# Installer logs
pip-log.txt
pip-delete-this-directory.txt

# Unit test / coverage reports
htmlcov/
.tox/
.nox/
.coverage
.coverage.*
.cache
nosetests.xml
coverage.xml
*.cover
*.py,cover
.hypothesis/
.pytest_cache/

# Translations
*.mo
*.pot

# Django stuff:
*.log
local_settings.py
db.sqlite3
db.sqlite3-journal
static/
media/
hidden_env/

# Flask stuff:
instance/
.webassets-cache

# Scrapy stuff:
.scrapy

# Sphinx documentation
docs/_build/

# PyBuilder
target/

# Jupyter Notebook
.ipynb_checkpoints

# IPython
profile_default/
ipython_config.py

# pyenv
.python-version

# pipenv
#   According to pypa/pipenv#598, it is recommended to include Pipfile.lock in version control.
#   However, in case of collaboration, if having platform-specific dependencies or dependencies
#   having no cross-platform support, pipenv may install dependencies that don't work, or not
#   install all needed dependencies.
#Pipfile.lock

# PEP 582; used by e.g. github.com/David-OConnor/pyflow
__pypackages__/

# Celery stuff
celerybeat-schedule
celerybeat.pid

# SageMath parsed files
*.sage.py

# Environments
.env
.venv
env/
venv/
ENV/
env.bak/
venv.bak/

# Spyder project settings
.spyderproject
.spyproject

# Rope project settings
.ropeproject

# mkdocs documentation
/site

# mypy
.mypy_cache/
.dmypy.json
dmypy.json

# Pyre type checker
.pyre/
```

Create a .env file, add the secret key there and all other secrets. Check out python decouple

**Comment by fracergu** [comment]
Hi @devvspaces, thanks for the advice. I am not very experienced with Python backends.

I have added the suggested `.gitignore` for the backend part, and I have configured `settings.py` to load the variables from the `.env` file, so now there should not be any database configuration variables in the code.

I have also moved the Django's SECRET_KEY to the `.env` file, but Git Guardian keeps complaining. I have to leave now but I'll try to solve it later.

**Review by devvspaces — CHANGES_REQUESTED** [review]
Great work so far, you did a lot on such little info about python.

What's left now is to removed files that were not meant to be pushed that were already pushed.

That __pycache__. Use git rm -r --cached */__pycache__/* to remove all the staged pycache files

**Review by devvspaces — APPROVED** [review]
Great work @fracergu

**Comment by fracergu** [comment]
@devvspaces Thanks!

Can you please add `hacktoberfest-accepted` label to de PR to add it to my Hacktoberfest progress? Thank you.

Captura desde 2023-10-21 18-39-31

**Pull request merged**
